package cli

import (
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
)

func projectTypes(report scanReport) []string {
	if len(report.Manifests) == 0 {
		return []string{"unknown"}
	}
	for _, manifest := range report.Manifests {
		if manifest == "package.json" {
			return []string{"javascript-project"}
		}
		if manifest == "go.mod" {
			return []string{"go-project"}
		}
	}
	return []string{"project"}
}

func runInit(args []string, cwd string, stdin io.Reader, stdout io.Writer) error {
	contextDir := defaultDocDir
	entryFiles := []string{}
	explicitEntryFiles := false
	nonInteractive := false
	acceptCandidates := false
	interactive := false

	for i := 0; i < len(args); i++ {
		switch args[i] {
		case "--dir":
			if i+1 >= len(args) {
				return errors.New("docx init: --dir requires a value")
			}
			i++
			contextDir = args[i]
		case "--entry":
			if i+1 >= len(args) {
				return errors.New("docx init: --entry requires a value")
			}
			i++
			entryFiles = append(entryFiles, args[i])
			explicitEntryFiles = true
		case "--non-interactive":
			nonInteractive = true
		case "--accept-candidates":
			acceptCandidates = true
		case "--interactive":
			interactive = true
		default:
			return fmt.Errorf("docx init: unknown option %q", args[i])
		}
	}

	root, err := filepath.Abs(cwd)
	if err != nil {
		return err
	}
	if !explicitEntryFiles {
		entryFiles = defaultEntryFiles(root)
	}
	docRoot := filepath.Join(root, contextDir)
	for _, dir := range []string{
		docRoot,
		filepath.Join(docRoot, "rules"),
		filepath.Join(docRoot, "modules"),
		filepath.Join(docRoot, "changes"),
		filepath.Join(docRoot, "proposals"),
		filepath.Join(docRoot, "decisions"),
		filepath.Join(docRoot, "mistakes"),
		filepath.Join(docRoot, ".cache"),
		filepath.Join(docRoot, "local"),
		filepath.Join(docRoot, "tmp"),
	} {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return err
		}
	}

	projectName := filepath.Base(root)
	report, err := scanProject(root)
	if err != nil {
		return err
	}
	moduleMap := map[string]moduleMapEntry{}
	if interactive {
		decisions, err := readModuleDecisions(stdin, stdout, report.ModuleCandidates)
		if err != nil {
			return err
		}
		if err := writeDecidedModules(docRoot, contextDir, report, decisions, moduleMap); err != nil {
			return err
		}
	} else if nonInteractive || acceptCandidates {
		candidateStatus := "candidate"
		if acceptCandidates {
			candidateStatus = "confirmed"
		}
		for _, candidate := range report.ModuleCandidates {
			decision := decidedModule{Name: candidate.Name, Paths: candidate.Paths, Status: candidateStatus}
			if err := writeModuleDecision(docRoot, contextDir, report, decision, moduleMap); err != nil {
				return err
			}
		}
	}
	if err := writeJSON(filepath.Join(root, ".docx.json"), configFile{
		SchemaVersion:        schemaVersion,
		ContextDir:           contextDir,
		ContextSchemaVersion: schemaVersion,
		EntryFiles:           entryFiles,
		AI: aiConfig{
			Provider:       "",
			Command:        "",
			TimeoutSeconds: 120,
			ContextSources: []string{"docx"},
			Output:         "proposal-json",
		},
	}); err != nil {
		return err
	}

	if err := writeJSON(filepath.Join(docRoot, "index.json"), indexFile{
		SchemaVersion: schemaVersion,
		Project: indexProject{
			Name:             projectName,
			Type:             []string{"unknown"},
			PrimaryLanguages: []string{},
			Summary:          "Project context has been initialized but not scanned yet.",
		},
		ReadOrder: []readOrderEntry{
			{When: "always", Files: []string{contextDir + "/project.json", contextDir + "/rules/agent.md"}},
			{When: "editing module", Resolve: contextDir + "/modules/{module}.json"},
			{When: "changing behavior", Files: []string{contextDir + "/decisions/index.json", contextDir + "/changes/index.json"}},
			{When: "debugging or reviewing", Files: []string{contextDir + "/mistakes/index.json"}},
		},
		ModuleMap: moduleMap,
	}); err != nil {
		return err
	}

	if err := writeJSON(filepath.Join(docRoot, "project.json"), projectFile{
		SchemaVersion: schemaVersion,
		Name:          projectName,
		Types:         projectTypes(report),
		Summary:       "Project context has been initialized but not scanned yet.",
		Facts:         facts{Manifests: report.Manifests, LastScannedAt: ""},
	}); err != nil {
		return err
	}

	if err := writeJSON(filepath.Join(docRoot, "capabilities.json"), capabilitiesFile{
		SchemaVersion:               schemaVersion,
		AvailableAnalyzers:          availableAnalyzerCapabilities(report),
		MissingRecommendedAnalyzers: missingRecommendedAnalyzers(report),
		LastCheckedAt:               "",
	}); err != nil {
		return err
	}

	if err := writeTextIfMissing(filepath.Join(docRoot, "README.md"), "# Project Context\n\nGenerated by docx. Start with `index.json`.\n"); err != nil {
		return err
	}
	if err := writeTextIfMissing(filepath.Join(docRoot, "rules", "agent.md"), "# Agent Reading Protocol\n\nRead `.doc/index.json` first and follow `readOrder` progressively.\n"); err != nil {
		return err
	}

	for _, path := range []string{
		filepath.Join(docRoot, "changes", "index.json"),
		filepath.Join(docRoot, "proposals", "index.json"),
		filepath.Join(docRoot, "decisions", "index.json"),
		filepath.Join(docRoot, "mistakes", "index.json"),
	} {
		if err := writeJSON(path, map[string]interface{}{"schemaVersion": schemaVersion, "items": []interface{}{}}); err != nil {
			return err
		}
	}

	for _, entry := range uniqueStrings(entryFiles) {
		if err := upsertManagedBlock(filepath.Join(root, entry), agentBlock(contextDir)); err != nil {
			return err
		}
	}
	if err := upsertManagedBlock(filepath.Join(root, ".gitignore"), gitignoreBlock(contextDir)); err != nil {
		return err
	}

	fmt.Fprintf(stdout, "Initialized docx context in %s\n", contextDir)
	return nil
}

func defaultEntryFiles(root string) []string {
	var entries []string
	for _, entry := range []string{"AGENTS.md", "CLAUDE.md"} {
		if _, err := os.Stat(filepath.Join(root, entry)); err == nil {
			entries = append(entries, entry)
		}
	}
	if len(entries) == 0 {
		return []string{"AGENTS.md"}
	}
	return entries
}
